apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: ${CICD_PROJECT_ID}
  labels:
    field.cattle.io/projectId: ${CICD_PROJECT_NAME}
  name: greenhouse-${CICD_PROJECT_NAME}
---
kind: Service
apiVersion: v1
metadata:
  name: greenhouse-service
  namespace: greenhouse-${CICD_PROJECT_NAME}
spec:
  selector:
    app: greenhouse
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenhouse
  namespace: greenhouse-${CICD_PROJECT_NAME}
  labels:
    app: greenhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenhouse
  template:
    metadata:
      labels:
        app: greenhouse
    spec:
      containers:
      - name: maven
        image: ${CICD_LOCAL_REGISTRY}/example-greenhouse:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
